name: CI

on: [push]

jobs:
  test:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node
      with:
        node-version: 20
        cache: yarn

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn ci:test
